### ISSUE TITLE
Warning if e-mail address of the recipient is not the one of a site user

### ISSUE THREAD

**Issue by xxsimoxx** [KTS915/Email-Logs#1]
On this line the plugin tried to get the username from the recipent email address.

If it doesn't find it it throws a `Warning: Attempt to read property "display_name" on bool in .../wp-content/plugins/kts-email-logs/email-logs.php on line 34`

![image](https://user-images.githubusercontent.com/29772709/210073647-d08e2b70-304c-47af-be1b-d250b2b052dd.png)

**Comment by xxsimoxx** [comment]
If it can be helpful, [here](https://github.com/ClassicPress/Directory/pull/56) there is a temporary fix I've applied.

**Comment by KTS915** [comment]
Thanks! Why would someone not have a `display_name`?

**Comment by xxsimoxx** [comment]
The problem is not the `display_name`. It's that the user is not found. `wp_mail` can send mails also to addresses that are not of a registered user.

**Comment by KTS915** [comment]
Fixed in v.3.0.
